-- ΥΔΕ Studio G — Supabase Auth, ασφαλής αποθήκευση και RLS
-- Project: promitheies-dimou-rodou
-- Εκτέλεση: Supabase Dashboard → SQL Editor → Run

begin;

create table if not exists public.yde_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  specialty text not null default '',
  license_number text not null default '',
  role text not null default 'engineer' check (role in ('admin','engineer','viewer')),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.yde_projects (
  id text primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null default 'Νέο έργο ΥΔΕ',
  supply_number text not null default '',
  installation_type text not null default '',
  project_status text not null default 'draft' check (project_status in ('draft','finalized','archived')),
  data jsonb not null default '{}'::jsonb,
  revision integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists yde_projects_owner_idx on public.yde_projects(owner_id);
create index if not exists yde_projects_updated_idx on public.yde_projects(updated_at desc);

create table if not exists public.yde_project_members (
  project_id text not null references public.yde_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  permission text not null default 'view' check (permission in ('view','edit')),
  created_at timestamptz not null default now(),
  primary key (project_id,user_id)
);
create index if not exists yde_project_members_user_idx on public.yde_project_members(user_id);

create table if not exists public.yde_project_versions (
  id bigint generated by default as identity primary key,
  project_id text not null references public.yde_projects(id) on delete cascade,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists yde_project_versions_project_idx on public.yde_project_versions(project_id,created_at desc);

create table if not exists public.yde_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  project_id text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists yde_audit_log_user_idx on public.yde_audit_log(user_id,created_at desc);

create or replace function public.yde_is_active_user()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.yde_profiles p where p.id=auth.uid() and p.active=true); $$;

create or replace function public.yde_is_editor()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.yde_profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','engineer')); $$;

create or replace function public.yde_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.yde_profiles p where p.id=auth.uid() and p.active=true and p.role='admin'); $$;

create or replace function public.yde_can_view_project(p_project_id text)
returns boolean language sql stable security definer set search_path=public
as $$
  select public.yde_is_active_user() and (
    public.yde_is_admin()
    or exists(select 1 from public.yde_projects p where p.id=p_project_id and p.owner_id=auth.uid())
    or exists(select 1 from public.yde_project_members m where m.project_id=p_project_id and m.user_id=auth.uid())
  );
$$;

create or replace function public.yde_can_edit_project(p_project_id text)
returns boolean language sql stable security definer set search_path=public
as $$
  select public.yde_is_editor() and (
    public.yde_is_admin()
    or exists(select 1 from public.yde_projects p where p.id=p_project_id and p.owner_id=auth.uid())
    or exists(select 1 from public.yde_project_members m where m.project_id=p_project_id and m.user_id=auth.uid() and m.permission='edit')
  );
$$;

revoke all on function public.yde_is_active_user() from public;
revoke all on function public.yde_is_editor() from public;
revoke all on function public.yde_is_admin() from public;
revoke all on function public.yde_can_view_project(text) from public;
revoke all on function public.yde_can_edit_project(text) from public;
grant execute on function public.yde_is_active_user() to authenticated;
grant execute on function public.yde_is_editor() to authenticated;
grant execute on function public.yde_is_admin() to authenticated;
grant execute on function public.yde_can_view_project(text) to authenticated;
grant execute on function public.yde_can_edit_project(text) to authenticated;

create or replace function public.handle_new_yde_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.yde_profiles(id,email,full_name,active,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),false,'engineer')
  on conflict(id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_yde on auth.users;
create trigger on_auth_user_created_yde after insert or update of email on auth.users
for each row execute procedure public.handle_new_yde_user();

insert into public.yde_profiles(id,email,full_name,active,role)
select u.id,u.email,coalesce(u.raw_user_meta_data->>'full_name',''),false,'engineer' from auth.users u
on conflict(id) do update set email=excluded.email;

update public.yde_profiles
set active=true,role='admin',full_name=case when full_name='' then 'Βασίλειος Διακολιός' else full_name end,updated_at=now()
where lower(email)=lower('vasilis1730@gmail.com');

create or replace function public.yde_set_updated_at()
returns trigger language plpgsql set search_path=public
as $$ begin new.updated_at=now(); return new; end; $$;

drop trigger if exists yde_profiles_set_updated_at on public.yde_profiles;
create trigger yde_profiles_set_updated_at before update on public.yde_profiles
for each row execute procedure public.yde_set_updated_at();
drop trigger if exists yde_projects_set_updated_at on public.yde_projects;
create trigger yde_projects_set_updated_at before update on public.yde_projects
for each row execute procedure public.yde_set_updated_at();

create or replace function public.yde_prevent_owner_change()
returns trigger language plpgsql set search_path=public
as $$
begin
  if old.owner_id is distinct from new.owner_id and not public.yde_is_admin() then
    raise exception 'Δεν επιτρέπεται αλλαγή ιδιοκτήτη έργου';
  end if;
  return new;
end;
$$;
drop trigger if exists yde_projects_prevent_owner_change on public.yde_projects;
create trigger yde_projects_prevent_owner_change before update of owner_id on public.yde_projects
for each row execute procedure public.yde_prevent_owner_change();

alter table public.yde_profiles enable row level security;
alter table public.yde_projects enable row level security;
alter table public.yde_project_members enable row level security;
alter table public.yde_project_versions enable row level security;
alter table public.yde_audit_log enable row level security;

-- Αφαίρεση της παλιάς ανοικτής πολιτικής και επαναδημιουργία ασφαλών πολιτικών
DROP POLICY IF EXISTS yde_anon_all ON public.yde_projects;
DROP POLICY IF EXISTS yde_profiles_select ON public.yde_profiles;
DROP POLICY IF EXISTS yde_profiles_admin_insert ON public.yde_profiles;
DROP POLICY IF EXISTS yde_profiles_admin_update ON public.yde_profiles;
DROP POLICY IF EXISTS yde_profiles_admin_delete ON public.yde_profiles;
DROP POLICY IF EXISTS yde_projects_select ON public.yde_projects;
DROP POLICY IF EXISTS yde_projects_insert ON public.yde_projects;
DROP POLICY IF EXISTS yde_projects_update ON public.yde_projects;
DROP POLICY IF EXISTS yde_projects_delete ON public.yde_projects;
DROP POLICY IF EXISTS yde_members_select ON public.yde_project_members;
DROP POLICY IF EXISTS yde_members_manage ON public.yde_project_members;
DROP POLICY IF EXISTS yde_versions_select ON public.yde_project_versions;
DROP POLICY IF EXISTS yde_versions_insert ON public.yde_project_versions;
DROP POLICY IF EXISTS yde_audit_select ON public.yde_audit_log;
DROP POLICY IF EXISTS yde_audit_insert ON public.yde_audit_log;

create policy yde_profiles_select on public.yde_profiles for select to authenticated
using(id=auth.uid() or public.yde_is_admin());
create policy yde_profiles_admin_insert on public.yde_profiles for insert to authenticated
with check(public.yde_is_admin());
create policy yde_profiles_admin_update on public.yde_profiles for update to authenticated
using(public.yde_is_admin()) with check(public.yde_is_admin());
create policy yde_profiles_admin_delete on public.yde_profiles for delete to authenticated
using(public.yde_is_admin() and id<>auth.uid());

create policy yde_projects_select on public.yde_projects for select to authenticated
using(public.yde_can_view_project(id));
create policy yde_projects_insert on public.yde_projects for insert to authenticated
with check(public.yde_is_editor() and (owner_id=auth.uid() or public.yde_is_admin()));
create policy yde_projects_update on public.yde_projects for update to authenticated
using(public.yde_can_edit_project(id)) with check(public.yde_can_edit_project(id));
create policy yde_projects_delete on public.yde_projects for delete to authenticated
using(public.yde_is_admin() or (public.yde_is_editor() and owner_id=auth.uid()));

create policy yde_members_select on public.yde_project_members for select to authenticated
using(user_id=auth.uid() or public.yde_can_view_project(project_id));
create policy yde_members_manage on public.yde_project_members for all to authenticated
using(public.yde_is_admin() or exists(select 1 from public.yde_projects p where p.id=project_id and p.owner_id=auth.uid()))
with check(public.yde_is_admin() or exists(select 1 from public.yde_projects p where p.id=project_id and p.owner_id=auth.uid()));

create policy yde_versions_select on public.yde_project_versions for select to authenticated
using(public.yde_can_view_project(project_id));
create policy yde_versions_insert on public.yde_project_versions for insert to authenticated
with check(public.yde_can_edit_project(project_id) and owner_id=auth.uid());

create policy yde_audit_select on public.yde_audit_log for select to authenticated
using(user_id=auth.uid() or public.yde_is_admin());
create policy yde_audit_insert on public.yde_audit_log for insert to authenticated
with check(public.yde_is_active_user() and user_id=auth.uid());

revoke all on public.yde_profiles from anon;
revoke all on public.yde_projects from anon;
revoke all on public.yde_project_members from anon;
revoke all on public.yde_project_versions from anon;
revoke all on public.yde_audit_log from anon;
grant select on public.yde_profiles to authenticated;
grant select,insert,update,delete on public.yde_projects to authenticated;
grant select,insert,update,delete on public.yde_project_members to authenticated;
grant select,insert on public.yde_project_versions to authenticated;
grant select,insert on public.yde_audit_log to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('yde-documents','yde-documents',false,52428800)
on conflict(id) do update set public=false;

DROP POLICY IF EXISTS yde_storage_select ON storage.objects;
DROP POLICY IF EXISTS yde_storage_insert ON storage.objects;
DROP POLICY IF EXISTS yde_storage_update ON storage.objects;
DROP POLICY IF EXISTS yde_storage_delete ON storage.objects;

create policy yde_storage_select on storage.objects for select to authenticated
using(bucket_id='yde-documents' and public.yde_is_active_user() and (public.yde_is_admin() or (storage.foldername(name))[1]=auth.uid()::text));
create policy yde_storage_insert on storage.objects for insert to authenticated
with check(bucket_id='yde-documents' and public.yde_is_editor() and (storage.foldername(name))[1]=auth.uid()::text);
create policy yde_storage_update on storage.objects for update to authenticated
using(bucket_id='yde-documents' and public.yde_is_editor() and (public.yde_is_admin() or (storage.foldername(name))[1]=auth.uid()::text))
with check(bucket_id='yde-documents' and public.yde_is_editor() and (public.yde_is_admin() or (storage.foldername(name))[1]=auth.uid()::text));
create policy yde_storage_delete on storage.objects for delete to authenticated
using(bucket_id='yde-documents' and public.yde_is_editor() and (public.yde_is_admin() or (storage.foldername(name))[1]=auth.uid()::text));

commit;

select 'yde_profiles' object,count(*) rows from public.yde_profiles
union all select 'yde_projects',count(*) from public.yde_projects
union all select 'yde_project_members',count(*) from public.yde_project_members
union all select 'yde_project_versions',count(*) from public.yde_project_versions
union all select 'yde_audit_log',count(*) from public.yde_audit_log;
